language: python
python:
  - "3.4"
  - "3.6"
install:
  - "pip install -e .[test]"
  - "pip install coveralls"
script: "py.test -v --cov mapboxgl --cov-report term-missing"
after_success:
  - coveralls || echo "intermittent coveralls failure"
